# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget cudpp_1900x cudpp_hash_1900x)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target cudpp_1900x
add_library(cudpp_1900x SHARED IMPORTED)

set_target_properties(cudpp_1900x PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart_static.lib"
)

# Create imported target cudpp_hash_1900x
add_library(cudpp_hash_1900x SHARED IMPORTED)

set_target_properties(cudpp_hash_1900x PROPERTIES
  INTERFACE_LINK_LIBRARIES "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudart_static.lib;cudpp_1900x"
)

# Import target "cudpp_1900x" for configuration "Debug"
set_property(TARGET cudpp_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cudpp_1900x PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_1900x64d.lib"
  IMPORTED_LOCATION_DEBUG "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_1900x64d.dll"
  )

# Import target "cudpp_hash_1900x" for configuration "Debug"
set_property(TARGET cudpp_hash_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(cudpp_hash_1900x PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_hash_1900x64d.lib"
  IMPORTED_LOCATION_DEBUG "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_hash_1900x64d.dll"
  )

# Import target "cudpp_1900x" for configuration "Release"
set_property(TARGET cudpp_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cudpp_1900x PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_1900x64.lib"
  IMPORTED_LOCATION_RELEASE "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_1900x64.dll"
  )

# Import target "cudpp_hash_1900x" for configuration "Release"
set_property(TARGET cudpp_hash_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(cudpp_hash_1900x PROPERTIES
  IMPORTED_IMPLIB_RELEASE "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_hash_1900x64.lib"
  IMPORTED_LOCATION_RELEASE "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_hash_1900x64.dll"
  )

# Import target "cudpp_1900x" for configuration "MinSizeRel"
set_property(TARGET cudpp_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cudpp_1900x PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_1900x64.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_1900x64.dll"
  )

# Import target "cudpp_hash_1900x" for configuration "MinSizeRel"
set_property(TARGET cudpp_hash_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(cudpp_hash_1900x PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_hash_1900x64.lib"
  IMPORTED_LOCATION_MINSIZEREL "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_hash_1900x64.dll"
  )

# Import target "cudpp_1900x" for configuration "RelWithDebInfo"
set_property(TARGET cudpp_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cudpp_1900x PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_1900x64.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_1900x64.dll"
  )

# Import target "cudpp_hash_1900x" for configuration "RelWithDebInfo"
set_property(TARGET cudpp_hash_1900x APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(cudpp_hash_1900x PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/lib/cudpp_hash_1900x64.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "C:/ProjectX/GVDBX/GVDBX/source/shared_cudpp/bin/cudpp_hash_1900x64.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
